### ISSUE TITLE
Add random species pictures to landing page

### ISSUE THREAD

**Issue by aphillippy** [VGP/vgp.github.io#10]
The top-level landing page is too plain. Suggest adding a few random species pictures arranged in a grid below the data links, with random species reselected on page reload. Avoid using species without images :)

**Comment by brianwalenz** [comment]
Implemented in c6422c8dafcb7b55c898ac0b3971fc22504cce18.  It scans the _static_ files in the site, and displays/links to any image in assets/images.  Thanks to https://jekyllcodex.org/without-plugin/image-gallery/ for how to find the images.
